export default function Head() {
  return (
    <>
      <title>Yoora</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <meta property="og:site_name" content="Yoora" />
      <meta name="og:type" content="website" />
      <meta name="og:title" content="Yoora" />
      <meta
        name="og:description"
        content="Bringing companies and customers together, anywhere"
      />
      <meta property="og:url" content="https://yoora.vercel.app/" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
