import { getPost } from '@services/posts';

const fetchPost = async (slug: string) => {
  return getPost(slug);
};

type Props = {
  params: {
    slug: string;
  };
};

export default async function Head({ params }: Props) {
  const { data } = await fetchPost(params.slug);
  const post = data?.status === 404 ? null : data[0];

  return (
    <>
      <title>{`${post?.title} | Yoora`}</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <meta property="og:site_name" content="Yoora" />
      <meta name="og:type" content="article" />
      <meta name="og:title" content={post?.title} />
      <meta property="og:image" content={post?.image.src} />
      <meta
        property="og:url"
        content={`https://yoora.vercel.app/${post?.slug}`}
      />
      <meta
        property="og:description"
        content="Bringing companies and customers together, anywhere"
      />
    </>
  );
}
